//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace luxeService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="luxeService.Iemployee")]
    public interface Iemployee
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iemployee/Getall", ReplyAction="http://tempuri.org/Iemployee/GetallResponse")]
        System.Threading.Tasks.Task<string> GetallAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iemployee/Update", ReplyAction="http://tempuri.org/Iemployee/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iemployee/Delete", ReplyAction="http://tempuri.org/Iemployee/DeleteResponse")]
        System.Threading.Tasks.Task<int> DeleteAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IemployeeChannel : luxeService.Iemployee, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class IemployeeClient : System.ServiceModel.ClientBase<luxeService.Iemployee>, luxeService.Iemployee
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IemployeeClient() : 
                base(IemployeeClient.GetDefaultBinding(), IemployeeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_Iemployee.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IemployeeClient(EndpointConfiguration endpointConfiguration) : 
                base(IemployeeClient.GetBindingForEndpoint(endpointConfiguration), IemployeeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IemployeeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IemployeeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IemployeeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IemployeeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IemployeeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetallAsync()
        {
            return base.Channel.GetallAsync();
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(string data)
        {
            return base.Channel.UpdateAsync(data);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(string data)
        {
            return base.Channel.DeleteAsync(data);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Iemployee))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Iemployee))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:63782/Services/employee.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IemployeeClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_Iemployee);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IemployeeClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_Iemployee);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_Iemployee,
        }
    }
}
